name = "hassio-proxy-api"
main = "src/index.js"
compatibility_date = "2024-05-01"
node_compat = true

[vars]
AI_MODEL="@cf/meta/llama-4-scout-17b-16e-instruct"

[observability.logs]
enabled = true

[ai]
binding = "AI"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[[kv_namespaces]]
binding = "KV"
id = "8e30bb13e55843ec835a83f7106bdde3"

[[d1_databases]]
binding = "DB"
database_name = "hassio-agent"
database_id = "6fd26ae9-6e97-4293-983d-a4a3074f1aad"
migrations_dir = "migrations"